### ISSUE TITLE
cannot import name 'get_camera_frustum_geometry_nparray' from 'utils.vis_cam_traj' 

### ISSUE THREAD

**Issue by jiennyteng** [yitongx/sinerf#1]
when run the vis_learned_poses.py  , it reported
ImportError: cannot import name 'get_camera_frustum_geometry_nparray' from 'utils.vis_cam_traj' 

and there is no 'get_camera_frustum_geometry_nparray'  function in the 'utils.vis_cam_traj'  file

**Comment by yitongx** [comment]
Hi,

Thanks for reporting! 

Indeed I forgot to put 'get_camera_frustum_geometry_nparray()' into 'utils.vis_cam_traj'. This was what you got when you forgot to synchronize the remote repo with local codes :-(.

I have added the 'get_camera_frustum_geometry_nparray()', as well as a few minor changes. The tested plots on my computer look good. Hopes this update helps you,

Best,
Yitong
